config/routes.rb
Custbook::Application.routes.draw do
  root :to => 'pages#home', :as => :home, :via => :get
  match '/clients/:id/destroy' => 'clients#destroy', :as => :destroy_client, :via => :get
  match '/treatments/:id/destroy' => 'treatments#destroy', :as => :destroy_treatment, :via => :get
  resources :treatments
  resources :clients

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :additional_info, :allergy, :birthday, :cell, :country, :diabetes, :email, :found, :herpes, :name, :nid, :pregnancy, :psoriasis, :sensitive_skin, :steroids, :surname, :yellows, :herpes_info
  validates :surname, :presence => true
  before_save :update_birthday
  has_many :treatments

  def full_name
    return "#{self.name} #{self.surname}"
  end

  def update_birthday
    if self.nid.size >= 6 and self.birthday == nil
      self.birthday = Date.strptime("19"+self.nid[0..5],"%Y%m%d")
    end
  end
  
  def any_contraindications?
    if self.allergy or self.diabetes or self.herpes or self.pregnancy or self.psoriasis or self.sensitive_skin or self.steroids or self.yellows
      return true
    else
      return false
    end
  end
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  attr_accessible :additional_info, :client_id, :color, :correction, :date, :price, :ttype
  belongs_to :client
  def date_polish
  	return self[:date].strftime('%d-%m-%Y')
  end
  def young?
  	return (ActiveSupport::TimeZone['Warsaw'].parse(self.date.to_s) > 18.months.ago and ActiveSupport::TimeZone['Warsaw'].parse(self.date.to_s) < 16.months.ago)
  end
  def old?
  	return (ActiveSupport::TimeZone['Warsaw'].parse(self.date.to_s) > 30.months.ago and ActiveSupport::TimeZone['Warsaw'].parse(self.date.to_s) < 28.months.ago)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  expose(:client)
  expose(:clients) { Client.order("surname")}
  expose(:treatments) { client.treatments }

  respond_to :html

  def create
   client.save
   respond_with(client)
  end

  def update
    client.save
    respond_with(client)
  end

  def destroy
    client.treatments.each do |t|
      tr = Treatment.find(t.id)
      tr.destroy
    end
    client.destroy
    redirect_to clients_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  expose(:treatments_young) { Treatment.find(:all, :conditions => {:date => 18.months.ago..16.months.ago}, :include => :client)}
  expose(:treatments_old) {Treatment.find(:all, :conditions => {:date => 30.months.ago..28.months.ago}, :include => :client)}
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  expose(:treatment)
  expose(:treatments) { Treatment.includes(:client).order(:date)}
  respond_to :html

  def search
    #@treatments = Treatment.all
  end

  def show
   # @treatment = Treatment.find(params[:id])
  end

  def new
    #@treatment = Treatment.new
  end

  def edit
   # @treatment = Treatment.find(params[:id])
  end

  def create
    update_ttype(params)
    update_color(params)
    treatment.save
    respond_with treatment
  end

  def update
    update_ttype(params)
    update_color(params)
    treatment.save
    respond_with treatment
  end

  def destroy
    treatment.destroy
    redirect_to treatments_path
  end

  private

  def update_ttype (params)
    if params[:ttype_from_selection] != "new"
      params[:treatment][:ttype] = params[:ttype_from_selection]
    end
  end
  def update_color (params)
    if params[:color_from_selection] != "new"
      params[:treatment][:color] = params[:color_from_selection]
    end
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
	def nodata (argument)
		if argument.to_s.empty?
			return (raw "<span class='no-data'>#{t "details.absence"}</span>")
		else
			argument
		end
	end
	def nodatatext
		return raw "<span class='no-data'>#{t "details.absence"}</span>"
	end
	def pln (price)
		return number_to_currency(price, :unit => "zł", :precision => 2, :format => "%n %u", :separator => ",")
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
	def client_create_button
		return link_to (raw t "client.create.button"), new_client_path, :class => [:btn, "btn-success"]
	end
	def client_show_button (client)
		return link_to (raw t "client.show.button"), client, :class => [:btn, "btn-primary"]
	end
	def client_edit_button (client)
		return link_to (raw t "client.edit.button"), edit_client_path(client), :class => [:btn, "btn-info"]
	end
	def client_destroy_button (client)
		return link_to (raw t "client.delete.button"), destroy_client_path(client), :confirm => (t "client.delete.confirm"), :class => [:btn, "btn-danger"]
	end
	def clients_button
		return link_to (raw t "client.index.button"), clients_path, :class => [:btn, "btn-primary"]
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
	def treatment_create_button
		return link_to (raw t "treatment.create.button"), new_treatment_path, :class => [:btn, "btn-success"]
	end
	def treatment_show_button (treatment)
		return link_to (raw t "treatment.show.button"), treatment, :class => [:btn, "btn-primary"]
	end
	def treatment_edit_button (treatment)
		return link_to (raw t "treatment.edit.button"), edit_treatment_path(treatment), :class => [:btn, "btn-info"]
	end
	def treatment_destroy_button (treatment)
		return link_to (raw t "treatment.delete.button"),  destroy_treatment_path(treatment), :confirm => (t "treatment.delete.confirm"), :class => [:btn, "btn-danger"]
	end
    def treatment_correction (treatment)
        return (raw ((treatment.correction?) ? " <span class='label label-warning'>#{t 'treatment.correction.label'}</span>" : ""))
    end
    def treatment_old (treatment)
        return (raw ((treatment.old?) ? " <span class='label label-important'>#{t 'treatment.old'}</span>" : ""))
    end
    def treatment_young (treatment)
        return (raw ((treatment.young?) ? " <span class='label label-important'>#{t 'treatment.young'}</span>" : ""))
    end
    def treatments_button
    	return link_to (raw t "treatment.index.button"), treatments_path, :class => [:btn, "btn-primary"]
    end
    def treatment_labels(treatment)
    	return (raw (treatment_correction(treatment)+treatment_young(treatment)+treatment_old(treatment)))
    end
    def treatment_info_in_client (t)
		return ((t.ttype.to_s.empty?) ? "<span style='color: grey'>Nieznany rodzaj</span>" : t.ttype)+" &mdash; "+((t.color.to_s.empty?) ? "<span style='color: grey'>Nieznany kolor</span>" : t.color)+treatment_labels(t)
	end
end

app/views/clients/_clients_treatments.html.erb
<% if treatments.any? %>
	<% sum = 0 %>
	<ol>
		<% treatments.each do |t| %>
		<% sum += t.price.to_i %>
			<li><%= link_to t.date_polish, t%>: <%= raw treatment_info_in_client t %></li>
		<% end %>
	</ol>
	<p><strong><%= t "treatment.all_price" %>:</strong>	<%= pln(sum) %></p>
<% else %>
	<%= t "treatment.no_treatments" %>
<% end %>

app/views/clients/_form.html.erb
<%= form_for(client, :html => {:class => "form-horizontal"}) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation" class="alert alert-error alert-message block-message error">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
      <% client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :surname, (t "client.surname"), :class => "control-label" %><div class="controls">
    <%= f.text_field :surname %> <span class="help-inline"><%= t "required" %></span></div>
  </div>
  <div class="control-group">
    <%= f.label :name, (t "client.name"), :class => "control-label" %><div class="controls">
    <%= f.text_field :name %></div>
  </div>
  <div class="control-group">
    <%= f.label :nid, (t "client.nid"), :class => "control-label" %><div class="controls">
    <%= f.text_field :nid %></div>
  </div>
  <div class="control-group">
    <%= f.label :cell, (t "client.cell"), :class => "control-label" %><div class="controls">
    <%= f.text_field :cell %></div>
  </div>
  <div class="control-group">
    <%= f.label :country, (t "client.country"), :class => "control-label" %><div class="controls">
    <%= f.text_field :country %></div>
  </div>
  <div class="control-group">
    <%= f.label :email, (t "client.email"), :class => "control-label" %><div class="controls">
    <%= f.email_field :email %></div>
  </div>
  <div class="control-group">
    <label class="control-label"><%= t "client.contradictions" %></label><div class="controls">
    <label class="checkbox"><%= f.check_box :diabetes %> <span><%= t "client.diabetes" %></span></label>
    <label class="checkbox"><%= f.check_box :psoriasis %> <span><%= t "client.psoriasis" %></span></label>
    <label class="checkbox"><%= f.check_box :steroids %> <span><%= t "client.steroids" %></span></label>
    <label class="checkbox"><%= f.check_box :pregnancy %> <span><%= t "client.pregnancy" %></span></label>
    <label class="checkbox"><%= f.check_box :yellows %> <span><%= t "client.yellows" %></span></label>
    <label class="checkbox"><%= f.check_box :allergy %> <span><%= t "client.allergy" %></span></label>
    <label class="checkbox"><%= f.check_box :sensitive_skin %> <span><%= t "client.sensitive_skin" %></span></label>
    <label class="checkbox"><%= f.check_box :herpes %> <span><%= t "client.herpes" %></span></label>
    </div>
  </div>
  <div class="control-group" id="herpes_info_container">
    <%= f.label :herpes_info, (t "client.herpes_info"), :class => "control-label" %><div class="controls">
    <%= f.text_field :herpes_info %></div>
  </div>
  <div class="control-group">
    <%= f.label :found, (t "client.found"), :class => "control-label" %><div class="controls">
    <%= f.text_field :found %></div>
  </div>
  <div class="control-group">
    <%= f.label :additional_info, (t "client.additional_info"), :class => "control-label" %><div class="controls">
    <%= f.text_area :additional_info, :size => "10x5" %></div>
  </div>
  <div class="form-actions">
    <%= f.submit (t "client.submit"), :class => [:btn, "btn-primary"] %>
    <%= link_to (t "cancel"), clients_path, :class => [:btn] %></div>
<% end %>

<script>
  $(function() {if(!$("#client_herpes").is(':checked')) {$("#herpes_info_container").hide();} $("#client_herpes").live("click", function() {$("#herpes_info_container").toggle('fast');});});
</script>

app/views/clients/edit.html.erb
<div class="page-header"><h1><%= t "client.edit.text" %></h1></div>

<%= render 'form' %>

app/views/clients/index.html.erb
<div class="page-header"><h1><%= t "client.list" %></h1></div>
<div class="row">
<div class="span5">
<%= client_create_button %>
</div>
<div class="span4 pull-right">
<input type="text" class="filter" name="livefilter" placeholder="<%= t "search" %>" />
</div>
</div>
<br />
<script>
$(function() {
    $("table#sort").tablesorter({headers:{5:{sorter:false}}});
    $('table.live_filter').liveFilter('fade');
});
</script>
<table class="table table-bordered zebra-striped live_filter" id="sort">
<thead>
  <tr>
    <th class="header headerSortDown">#</th>
    <th class="green"><%= t "client.surname" %></th>
    <th class="blue"><%= t "client.name" %></th>
    <th class="red"><%= t "client.cell" %></th>
    <th class="orange"><%= t "client.email" %></th>
    <th class="header"><%= t "actions" %></th>
  </tr>
</thead>
<tbody>
<% if clients.any? %>
<% clients.each do |client| %>
  <tr>
    <td><%= client.id %></td>
    <td><%= client.surname %></td>
    <td><%= client.name %></td>
    <td><%= client.cell %></td>
    <td><%= mail_to client.email %></td>
    <td><div class="btn-group"><%= client_show_button client %>
    <%= client_edit_button client %>
    <%= client_destroy_button client %></div></td>
  </tr>
<% end %>
<% else %>
<tr><td colspan="6"><%= t "no_objects_to_display" %></td></tr>
<% end %>
</tbody>
</table>

app/views/clients/new.html.erb
<div class="page-header"><h1><%= t "client.new" %></h1></div>

<%= render 'form' %>

app/views/clients/show.html.erb
<div class="page-header">
<h1><%= client.full_name %></h1>
</div>
<% if notice != nil %>
<div class="alert-message alert alert-success" id="notice"><strong><%= notice %></strong></div>
<% end %>
<div class="row">
<div class="btn-group pull-right">
<%= client_edit_button client %>
<%= client_destroy_button client %>
</div>
</div>
<hr />
<div class="row">
<div class="span4">
<p><strong><%= t "client.birthday" %>:</strong> <%= client.birthday.nil? ? nodatatext : client.birthday %></p>
<p><strong><%= t "client.nid" %>:</strong> <%= nodata client.nid %></p>
<p><strong><%= t "client.cell" %></strong> <%= nodata client.cell %></p>
<p><strong><%= t "client.country" %>:</strong> <%= nodata client.country %></p>
<p><strong><%= t "client.email" %>:</strong> <%= client.email.empty? ? nodatatext : (mail_to client.email) %></p>
<p><strong><%= t "client.created_at" %>:</strong> <%= client.created_at.strftime("%d-%m-%Y") %></p>
<p><strong><%= t "client.found" %>:</strong> <%= nodata client.found %></p>
<strong><%= t "client.contraindications" %>:</strong><br /><% if client.any_contraindications? %><ul>
<% if client.diabetes %><li><%= t "client.diabetes" %></li><% end %>
<% if client.psoriasis %><li><%= t "client.psoriasis" %></li><% end %>
<% if client.steroids %><li><%= t "client.steroids" %></li><% end %>
<% if client.pregnancy %><li><%= t "client.pregnancy" %></li><% end %>
<% if client.yellows %><li><%= t "client.yellows" %></li><% end %>
<% if client.allergy %><li><%= t "client.allergy" %></li><% end %>
<% if client.sensitive_skin %><li><%= t "client.sensitive_skin" %></li><% end %>
<% if client.herpes %><li><%= t "client.herpes" %><% if !client.herpes_info.empty? %> (<%= client.herpes_info%>)<% end %></li><% end %>
</ul>
<% else %>
<%= nodatatext %><% end %>
<p><strong><%= t "client.additional_info" %>:</strong><br />
<%= nodata client.additional_info %></p>
</div>
<div class="span6">
<h2 id="treatments"><%= t "client.treatments" %></h2>
<%= render 'clients_treatments' %>
<hr />
<div class="well">
<%= render :partial => 'treatments/form_small', :locals => {:treatment => Treatment.new({:client_id => client.id})} %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Custbook</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <!--<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"/>-->
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <!-- iPhone -->
        <link href="<%= image_path 'apple-touch-icon-57x57.png' %>"
              sizes="57x57"
              rel="apple-touch-icon">
        <!-- iPad -->
        <link href="<%= image_path 'apple-touch-icon-72x72.png' %>"
              sizes="72x72"
              rel="apple-touch-icon">
        <!-- iPhone (Retina) -->
        <link href="<%= image_path 'apple-touch-icon-114x114.png' %>"
              sizes="114x114"
              rel="apple-touch-icon">
        <!-- iPad (Retina) -->
        <link href="<%= image_path 'apple-touch-icon-144x144.png' %>"
              sizes="144x144"
              rel="apple-touch-icon">

        <!-- iPhone -->
        <link href="<%= image_path 'apple-touch-startup-image-320x460.png' %>"
              media="(device-width: 320px)"
              rel="apple-touch-startup-image">
        <!-- iPhone (Retina) -->
        <link href="<%= image_path 'apple-touch-startup-image-640x920.png' %>"
              media="(device-width: 320px)
                 and (-webkit-device-pixel-ratio: 2)"
              rel="apple-touch-startup-image">
        <!-- iPad (portrait) -->
        <link href="<%= image_path 'apple-touch-startup-image-768x1004.png' %>"
              media="(device-width: 768px)
                 and (orientation: portrait)"
              rel="apple-touch-startup-image">
        <!-- iPad (landscape) -->
        <link href="<%= image_path 'apple-touch-startup-image-748x1024.png' %>"
              media="(device-width: 768px)
                 and (orientation: landscape)"
              rel="apple-touch-startup-image">
        <!-- iPad (Retina, portrait) -->
        <link href="<%= image_path 'apple-touch-startup-image-1536x2008.png' %>"
              media="(device-width: 768px)
                 and (orientation: portrait)
                 and (-webkit-device-pixel-ratio: 2)"
              rel="apple-touch-startup-image">
        <!-- iPad (Retina, landscape) -->
        <link href="<%= image_path 'apple-touch-startup-image-1496x2048.png' %>"
              media="(device-width: 768px)
                 and (orientation: landscape)
                 and (-webkit-device-pixel-ratio: 2)"
              rel="apple-touch-startup-image">
</head>
<body>
<div class="header navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Custbook", home_path, :class => :brand %>
			<ul class="nav">
				<li><%= link_to (t "client.many"), clients_path, :class => :left %></li>
				<li><%= link_to "+", new_client_path, :class => :right %></li>
				<li><%= link_to (t "treatment.many"), treatments_path, :class => :left %></li>
				<li><%= link_to "+", new_treatment_path, :class => :right %></li>
			</ul>
		</div>
	</div>
</div>
<div class="container">
	<div class="content">
<%= yield %>
	</div>
	<footer><br /></footer>
</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="page-header"><h1><%= t "home.heading" %></h1></div>
<div class="row"><div class="span6">
<% if treatments_old.any? %>
    <h3><%= t "treatment.old_long" %>:</h3>
    <ul>
        <% treatments_old.each do |t| %>
            <li><%= link_to t.client.full_name, t.client %><% if !t.client.email.empty? %> &lt;<%= mail_to t.client.email %>&gt;<% end %><% if !t.client.cell.empty? %> (<%= t "client.tel" %><%= t.client.cell %>)<% end %>: <%= link_to t.ttype, t %> w dniu <%= t.date %></li><br />
        <% end %>
    </ul>
<% end %>
<% if (treatments_old.any? and treatments_young.any?) %>
    <hr />
<% end %>
<% if treatments_young.any? %>
    <h3><%= t "treatment.young_long" %>:</h3>
    <ul>
        <% treatments_young.each do |t| %>
            <li><%= link_to t.client.full_name, t.client %><% if !t.client.email.empty? %> &lt;<%= mail_to t.client.email %>&gt;<% end %><% if !t.client.cell.empty? %> (<%= t "client.tel" %><%= t.client.cell %>)<% end %>: <%= link_to t.ttype, t %><%= t "treatment.at" %><%= t.date %> <%= treatment_correction(t) %></li><br />
        <% end %>
    </ul>
<% end %>
<% if !(treatments_old.any? or treatments_young.any?) %>
    <p><%= t "treatment.no_special" %></p>
<% end %>
</div>
<div class="span4">
    <%= client_create_button %>
    <hr />
    <%= treatment_create_button %>
    <hr />
    <%= clients_button %>
    <hr />
    <%= treatments_button %>
</div></div>

app/views/treatments/_form.html.erb
<%= form_for(treatment, :html => {:class => "form-horizontal"}) do |f| %>
  <% if treatment.errors.any? %>
    <div id="error_explanation" class="alert-message error block-message">
      <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% treatment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :client_id, (t "client.one"), :class => "control-label" %><div class="controls">
   <%= f.select :client_id, Client.order(:surname).all.collect {|p| [(p.surname+" "+p.name), p.id]}, :include_blank => true %></div>
  </div>
  <div class="control-group">
    <%= f.label :ttype, (t "treatment.ttype.text"), :class => "control-label" %><div class="controls">
      <select name="ttype_from_selection" id="ttype_from_selection">
        <option value=""></option>
        <option value="new"><%= (t "add.new_masculine") %></option>
      <%= options_from_collection_for_select(Treatment.where("ttype != ''").select("DISTINCT(ttype)").order(:ttype),"ttype","ttype") %>
    </select>
    <%= f.text_field :ttype, :id => "new_ttype", :placeholder => (t "treatment.ttype.name") %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, (t "treatment.price"), :class => "control-label" %><div class="controls"><div class="input-append">
    <%= f.number_field :price %><span class="add-on">zł</span></div></div>
  </div>
  <div class="control-group">
    <%= f.label :color, (t "treatment.color.text"), :class => "control-label" %><div class="controls">
    <select name="color_from_selection" id="color_from_selection">
        <option value=""></option>
        <option value="new"><%= (t "add.new_masculine") %></option>
      <%= options_from_collection_for_select(Treatment.where("color != ''").select("DISTINCT(color)").order(:color),"color","color") %>
    </select>
    <%= f.text_field :color, :id => "new_color", :placeholder => (t "treatment.color.name") %></div>
  </div>
  <div class="control-group">
    <%= f.label :date, (t "treatment.date"), :class => "control-label" %><div class="controls">
    <%= f.date_select :date, :order => [:day, :month, :year] %></div>
  </div>
  <div class="control-group">
    <%= f.label :correction, (t "treatment.correction.text"), :class => "control-label" %><div class="controls">
    <%= f.check_box :correction %></div>
  </div>
  <div class="control-group">
    <%= f.label :additional_info, (t "treatment.additional_info"), :class => "control-label" %><div class="controls"><%= f.text_area :additional_info, :size => "40x7" %></div>
  </div>
  <div class="form-actions">
    <%= f.submit (t "treatment.submit"), :class => [:btn, "btn-primary"] %>
    <%= link_to (t "cancel"), treatments_path, :class => [:btn] %>
  </div>
<% end %>
<script>
  $(function(){$("#new_ttype").hide();<% if treatment.ttype %>$("#ttype_from_selection option").each(function(el) {if($(this).text() == "<%= treatment.ttype %>") { $(this).attr("selected", "selected");}});<% end %>$("#ttype_from_selection").live("change", function(){if($("#ttype_from_selection option:selected").text() == "Dodaj nowy") {$("#new_ttype").show();} else { $("#new_ttype").hide();}})})
  $(function(){$("#new_color").hide();<% if treatment.color %>$("#color_from_selection option").each(function(el) {if($(this).text() == "<%= treatment.color %>") { $(this).attr("selected", "selected");}});<% end %>$("#color_from_selection").live("change", function(){if($("#color_from_selection option:selected").text() == "Dodaj nowy") {$("#new_color").show();} else { $("#new_color").hide();}})})
</script>

app/views/treatments/_form_small.html.erb
<h2><%= t "treatment.add.heading" %></h2>
<%= form_for(treatment, :html => {:class => "form-vertical small-treatment-form"}) do |f| %>
<input type="hidden" name="small" value="true" />
  <%= f.hidden_field :client_id %>
  <div class="control-group">
    <%= f.label :ttype, (t "treatment.ttype.text"), :class => "control-label" %><div class="controls">
      <select name="ttype_from_selection" id="ttype_from_selection">
        <option value=""></option>
        <option value="new"><%= (t "add.new_masculine") %></option>
      <%= options_from_collection_for_select(Treatment.where("ttype != ''").select("DISTINCT(ttype)").order(:ttype),"ttype","ttype") %>
    </select>
    <%= f.text_field :ttype, :id => "new_ttype", :placeholder => (t "treatment.ttype.name") %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, (t "treatment.price"), :class => "control-label" %><div class="controls"><div class="input-append">
    <%= f.number_field :price %><span class="add-on">zł</span></div></div>
  </div>
  <div class="control-group">
    <%= f.label :color, (t "treatment.color.text"), :class => "control-label" %><div class="controls">
    <select name="color_from_selection" id="color_from_selection">
        <option value=""></option>
        <option value="new"><%= (t "add.new_masculine") %></option>
      <%= options_from_collection_for_select(Treatment.where("color != ''").select("DISTINCT(color)").order(:color),"color","color") %>
    </select>
    <%= f.text_field :color, :id => "new_color", :placeholder => (t "treatment.color.name") %></div>
  </div>
  <div class="control-group">
    <%= f.label :date, (t "treatment.date"), :class => "control-label" %><div class="controls">
    <%= f.date_select :date, :order => [:day, :month, :year] %></div>
  </div>
  <div class="control-group">
    <%= f.label :correction, (t "treatment.correction.text"), :class => "control-label" %><div class="controls">
    <%= f.check_box :correction %></div>
  </div>
  <div class="control-group">
    <%= f.label :additional_info, (t "treatment.additional_info"), :class => "control-label" %><div class="controls"><%= f.text_area :additional_info, :size => "40x7" %></div>
  </div>
  <div class="form-actions">
    <%= f.submit (t "treatment.submit"), :class => [:btn, "btn-primary"] %>
    <%= link_to (t "cancel"), treatments_path, :class => [:btn] %>
  </div>
<% end %>
<script>
  $(function(){$("#new_ttype").hide();$("#ttype_from_selection").live("change", function(){if($("#ttype_from_selection option:selected").text() == "Dodaj nowy") {$("#new_ttype").show();} else { $("#new_ttype").hide();}})})
  $(function(){$("#new_color").hide();$("#color_from_selection").live("change", function(){if($("#color_from_selection option:selected").text() == "Dodaj nowy") {$("#new_color").show();} else { $("#new_color").hide();}})})
</script>

app/views/treatments/edit.html.erb
<div class="page-header"><h1><%= t "treatment.edit.text" %></h1></div>

<%= render 'form' %>

app/views/treatments/new.html.erb
<div class="page-header"><h1><%= t "treatment.new" %></h1></div>

<%= render 'form' %>